name: Test Deploy Request
description: Provide the required Azure resource identifiers.
title: "[Test Deploy Request]: "
labels:
  - deploy
body:
  - type: input
    id: suscription_id
    attributes:
      label: suscription_id
      description: Enter the Azure subscription identifier.
      placeholder: 00000000-0000-0000-0000-000000000000
    validations:
      required: true

  - type: input
    id: resource_group
    attributes:
      label: resource_group
      description: Enter the Azure resource group name.
      placeholder: my-resource-group
    validations:
      required: true

  - type: input
    id: resource_name
    attributes:
      label: resource_name
      description: Enter the Azure resource name.
      placeholder: my-resource
    validations:
      required: true

  - type: input
    id: resource_type
    attributes:
      label: resource_type
      description: Enter the Azure resource type.
      placeholder: my-resource-type

