name: Deploy to Vercel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore SOLIDapp/SOLIDapp.Web/SOLIDapp.Web.csproj

      - name: Publish Blazor WASM
        run: dotnet publish SOLIDapp/SOLIDapp.Web/SOLIDapp.Web.csproj -c Release -o build

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Create Vercel project (CLI, idempotent)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          PROJECT_NAME: ${{ github.event.repository.name }}
        run: |
          if [ -z "$VERCEL_TOKEN" ]; then
            echo "VERCEL_TOKEN not set; skipping project creation."
            exit 0
          fi
          echo "Ensuring Vercel project exists: $PROJECT_NAME"
          if [ -n "$VERCEL_ORG_ID" ]; then
            vercel projects add "$PROJECT_NAME" --team "$VERCEL_ORG_ID" --token "$VERCEL_TOKEN" --yes || echo "Project may already exist; continuing..."
          else
            vercel projects add "$PROJECT_NAME" --token "$VERCEL_TOKEN" --yes || echo "Project may already exist; continuing..."
          fi

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          PROJECT_NAME: ${{ github.event.repository.name }}
        run: |
          echo "Deploying project: $PROJECT_NAME"
          # If VERCEL_ORG_ID is set, pass --org, otherwise omit
          if [ -n "$VERCEL_ORG_ID" ]; then
            vercel --confirm --token "$VERCEL_TOKEN" --cwd build/wwwroot --prod --team "$VERCEL_ORG_ID" --project "$PROJECT_NAME"
          else
            vercel --confirm --token "$VERCEL_TOKEN" --cwd build/wwwroot --prod --project "$PROJECT_NAME"
          fi
